print('lets see what can i do for you guys')
print('hello eveyone my name is anzum' ,end='')
print('bhai i dont know really myself about anything')
print('lets try something new', 'what is this new?')
print('like my name is anzum''i am 23 years old')
print('c:\\oktim')
print('anzum and roktim \n both are good boys \t1')